services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - ./db_data:/app/data
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
