"""add calls and reschedules tables

Revision ID: 77e748f561b0
Revises: 9d0090a203db
Create Date: 2026-04-22 01:28:12.864250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e748f561b0'
down_revision: Union[str, None] = '9d0090a203db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerated via:
    #   ./.venv/bin/alembic revision --autogenerate -m "add calls and reschedules tables"
    #
    # SQLite reports unrelated UUID/Enum type diffs on existing tables, so this
    # revision intentionally keeps only the new automation tables and indexes.
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('vapi_call_id', sa.String(length=255), nullable=True),
    sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'IN_PROGRESS', 'COMPLETED', 'NO_ANSWER', 'VOICEMAIL', 'BUSY', 'FAILED', 'REFUSED', name='callstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('structured_answers', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentimenttype'), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vapi_call_id')
    )
    op.create_index('ix_calls_client_id', 'calls', ['client_id'], unique=False)
    op.create_index('ix_calls_status', 'calls', ['status'], unique=False)
    op.create_table('reschedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('original_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reschedules_client_id', 'reschedules', ['client_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_reschedules_client_id', table_name='reschedules')
    op.drop_table('reschedules')
    op.drop_index('ix_calls_status', table_name='calls')
    op.drop_index('ix_calls_client_id', table_name='calls')
    op.drop_table('calls')
