"""expand clients for automation

Revision ID: 9d0090a203db
Revises: 03fe9af8fe7c
Create Date: 2026-04-22 01:13:20.810599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0090a203db'
down_revision: Union[str, None] = '03fe9af8fe7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerated via:
    #   ./.venv/bin/alembic revision --autogenerate -m "expand clients for automation"
    #
    # SQLite reports noisy type diffs here for UUID/Enum columns, so we keep only
    # the real schema additions for this project phase.
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('clients', sa.Column('reschedule_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('clients', sa.Column('last_call_attempt_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column('clients', 'last_call_attempt_at')
    op.drop_column('clients', 'reschedule_count')
    op.drop_column('clients', 'is_active')
